I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 183, in script
    $ renpy.save(persistent.last_save_slot)
  File "game/script.rpy", line 183, in <module>
    $ renpy.save(persistent.last_save_slot)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 183, in script
    $ renpy.save(persistent.last_save_slot)
  File "/home/yallicol/renpy-sdk/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/yallicol/renpy-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 183, in <module>
    $ renpy.save(persistent.last_save_slot)
  File "/home/yallicol/renpy-sdk/renpy/loadsave.py", line 460, in save
    location.save(slotname, sr)
  File "/home/yallicol/renpy-sdk/renpy/savelocation.py", line 517, in save
    l.save(slotname, record)
  File "/home/yallicol/renpy-sdk/renpy/savelocation.py", line 208, in save
    filename = self.filename(slotname)
  File "/home/yallicol/renpy-sdk/renpy/savelocation.py", line 146, in filename
    return os.path.join(self.directory, renpy.exports.fsencode(slotname + renpy.savegame_suffix))
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Linux-6.8.9-100.fc38.x86_64-x86_64-with-glibc2.37 x86_64
Ren'Py 8.3.4.24120703
src 1.0
Wed Feb 19 11:35:23 2025
