I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 554, in script call
    call nao_disconnect()
  File "game/script.rpy", line 554, in script call
    call nao_disconnect()
ScriptError: could not find label 'nao_disconnect'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 554, in script call
    call nao_disconnect()
  File "C:\RenPy\renpy-8.3.7-sdk\renpy\ast.py", line 1427, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 554, in script call
    call nao_disconnect()
  File "C:\RenPy\renpy-8.3.7-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'nao_disconnect'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.3.7.25031702
src 1.0
Wed Apr  2 18:27:20 2025
