I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 411, in script
    python:
  File "game/script.rpy", line 413, in <module>
    renpy.call_screen("godspeed_questionnaire", q, q["var"])
  File "game/screens.rpy", line 1819, in execute
    screen godspeed_questionnaire(question, storevar):
  File "game/screens.rpy", line 1819, in execute
    screen godspeed_questionnaire(question, storevar):
  File "game/screens.rpy", line 1822, in execute
    frame:
  File "game/screens.rpy", line 1826, in execute
    has vbox
  File "game/screens.rpy", line 1828, in execute
    hbox:
  File "game/screens.rpy", line 1832, in execute
    text question["start"] xalign 0.0 size 24
  File "game/screens.rpy", line 1832, in <module>
    text question["start"] xalign 0.0 size 24
KeyError: 'start'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 411, in script
    python:
  File "/home/yallicol/renpy-sdk/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/yallicol/renpy-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 413, in <module>
    renpy.call_screen("godspeed_questionnaire", q, q["var"])
  File "/home/yallicol/renpy-sdk/renpy/exports/statementexports.py", line 345, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/home/yallicol/renpy-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/yallicol/renpy-sdk/renpy/display/core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/yallicol/renpy-sdk/renpy/display/core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/yallicol/renpy-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/home/yallicol/renpy-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/home/yallicol/renpy-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/home/yallicol/renpy-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "/home/yallicol/renpy-sdk/renpy/display/core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/home/yallicol/renpy-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "/home/yallicol/renpy-sdk/renpy/display/screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 1819, in execute
    screen godspeed_questionnaire(question, storevar):
  File "game/screens.rpy", line 1819, in execute
    screen godspeed_questionnaire(question, storevar):
  File "game/screens.rpy", line 1822, in execute
    frame:
  File "game/screens.rpy", line 1826, in execute
    has vbox
  File "game/screens.rpy", line 1828, in execute
    hbox:
  File "game/screens.rpy", line 1832, in execute
    text question["start"] xalign 0.0 size 24
  File "game/screens.rpy", line 1832, in <module>
    text question["start"] xalign 0.0 size 24
KeyError: 'start'

Linux-6.8.9-100.fc38.x86_64-x86_64-with-glibc2.37 x86_64
Ren'Py 8.3.4.24120703
src 1.0
Wed Mar 26 12:55:24 2025
